import { ClerkProvider } from '@clerk/nextjs';
import { GeistSans } from "geist/font/sans";
import { type AppType } from "next/app";
import { Box, ChakraProvider } from '@chakra-ui/react'


import { api } from "~/utils/api";

import "~/styles/globals.css";
import { PageHeader, PageFooter } from '~/components';
import Head from 'next/head';

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <ClerkProvider {...pageProps}>
      <ChakraProvider>
        <Head>
          <title>FIXR</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/spanner.ico" />
        </Head>
        <div className={GeistSans.className}>
          <Box pt={5} px={10}>
            <PageHeader />
          </Box>
          <Component {...pageProps} />
          <Box px={10}>
            <PageFooter />
          </Box>
        </div>
      </ChakraProvider>
    </ClerkProvider>
  );
};

export default api.withTRPC(MyApp);
