/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import Head from "next/head";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import { Flex } from "@chakra-ui/react";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Flex>
          {!user.isSignedIn && (<SignInButton />)}
          {!!user.isSignedIn && (<SignOutButton />)}
        </Flex>
      </main >
    </>
  );
}
