/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import Head from "next/head";

import { Box } from "@chakra-ui/react";
import { SignedIn, SignedOut, useUser } from "@clerk/nextjs";
import LandingPage from "~/components/LandingPage";
import { PageHeader } from "~/components/PageHeader";
import styles from "./index.module.css";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box p={10}>
          <PageHeader />
          <SignedOut>
            <LandingPage />
          </SignedOut>
          <SignedIn>
            <LandingPage />
          </SignedIn>
        </Box>
      </main>
    </>
  );
}
